COPY website_user(username,email,password) from '/tmp/Work_so_far/data_generation/website_users.csv' delimiter ',' csv;
COPY follows(follower,is_followed) from '/tmp/Work_so_far/data_generation/follows.csv' delimiter ',' csv;
COPY game(name,releaseyear,description,genre) from '/tmp/Work_so_far/data_generation/game.csv' delimiter ',' csv;
COPY mod_for_game(game_name,game_release_year,modId,name,link,description) from '/tmp/Work_so_far/data_generation/mod_for_game.csv' delimiter ',' csv;
BEGIN;
COPY post(username,game_name,game_release_year,title,date,time,body) from '/tmp/Work_so_far/data_generation/post.csv' delimiter ',' csv;
COPY post_features_mod(modId,title,date,time,config_importance_rating) from '/tmp/Work_so_far/data_generation/post_features_mod.csv' delimiter ',' csv;
COMMIT;
COPY comment_for_post(post_title,post_date,post_time,comment_date,comment_time,comment_body,username) from '/tmp/Work_so_far/data_generation/comment_for_post.csv' delimiter ',' csv;
COPY visits(username,title,date,time,most_recent_visit_date) from '/tmp/Work_so_far/data_generation/visits.csv' delimiter ',' csv;
COPY favorites(username,title,date,time,favorite_date,favorite_time) from '/tmp/Work_so_far/data_generation/favorites.csv' delimiter ',' csv;
COPY add_on_mod(modId,hours_added,num_new_items) from '/tmp/Work_so_far/data_generation/add_on_mod.csv' delimiter ',' csv;
COPY graphical_mod(modId,resolution,fps) from '/tmp/Work_so_far/data_generation/graphical_mod.csv' delimiter ',' csv;
COPY unofficial_patch_mod(modId,version) from '/tmp/Work_so_far/data_generation/unofficial_patch_mod.csv' delimiter ',' csv;
